"""add lists, list items, and asset goal

Revision ID: 7f0c2ed8855d
Revises: bda3b52a7056
Create Date: 2026-08-13 15:57:47.057571
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '7f0c2ed8855d'
down_revision: str | None = 'bda3b52a7056'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('next_step', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_list_user_name')
    )
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.create_index('ix_lists_user_position', ['user_id', 'position'], unique=False)

    op.create_table('list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('list_items', schema=None) as batch_op:
        batch_op.create_index('ix_list_items_list_position', ['list_id', 'position'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_items', schema=None) as batch_op:
        batch_op.drop_index('ix_list_items_list_position')

    op.drop_table('list_items')
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_index('ix_lists_user_position')

    op.drop_table('lists')
    op.drop_table('asset_goals')
    # ### end Alembic commands ###
